language: en
pipeline:
- name: SpacyNLP
  model: en_core_web_md
  case_sensitive: false
- name: SpacyTokenizer
- name: SpacyFeaturizer
  pooling: mean
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: SpacyEntityExtractor
  dimensions: ["LOC"]
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1
policies:
- name: AugmentedMemoizationPolicy
- name: TEDPolicy
- name: RulePolicy
